### PR TITLE
Add two functions

### PR DESCRIPTION
**Pull request by hyginn**
# Pull request for two added functions: `qrandommaxint()` and `qUUID()`

(Nb. Congratulations on this fine package - und herzlichen Gruß nach Regensburg)

## Description

I offer to contribute two functions to extend the use of qrandom to two use cases. 

`qrandommaxint()` is for generating uniformly distributed signed integers directly from the hex-stream.  

`qUUID()` creates RFC 4122 compliant UUIDs.

## Motivation and Context

Regarding `qrandommaxint()`, the generation of signed integers from multiplying the range `[-.Machine$integer.max; .Machine$integer.max]` with numbers from U(0, 1) is not completely sound (cf. [Ottoboni & Stark, 2018](https://www.stat.berkeley.edu/~stark/Preprints/r-random-issues.pdf)). Generating such integers reliably is difficult since the RNG seed space is very much smaller than the number space. Thus an interesting use is for initializing the RNG with `set.seed(qrandommaxint())`. The code is not entirely trivial, since the inbuilt `strtoi()` function fails for negative integers. Thus only numbers from `0x00000000` to `0x7ffffffff` are available using available R tools. 

A similar issue arises with UUIDs, where the distribution of RNG generated UUIDs may suffer from ill-chosen RNG seeds. Thus generating such 128 bit numbers (122 random bits) from true random numbers is desirable. However making the numbers RFC 4122 compliant is not entirely trivial, it requires converting the hex-pattern to bits, stamping the required 6-bit version information, re-converting to hex, and adding four hyphens.

Along with adding the sources into `./R` I have created the two `./man/...Rd` files, exported the functions via `NAMESPACE`, bumped the version number to 1.1, created an appropriate entry for `NEWS`, updated `README.md`, added my name in a `"ctb"` role to `DESCRIPTION`, and added two `./tests/testthat/test-....R` files. I believe that this makes the contribution complete and results in a fully CRAN compliant package without need for further change.

These functions require no additional dependencies.

## How Has This Been Tested?
The tests are included in `./tests/testthat/test-qrandommax.R` and `./tests/testthat/test-qUUID.R`. I test internal functions and valid output.

RStudios menu driven R CMD check passes without errors, warnings or notes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by hyginn** [comment]
I just saw a failed appveyor result, affecting a test in my `qrandommaxint()` (plus two of your functions that I did not change). The failing line in my test is
`x <- qrandommaxint(2)` and since that is not a test but calls `qrandom()` internally, and then transforms the output, I suspect that there is an underlying problem in getting the Web connection set up on the appveyor platform.

**Comment by skoestlmeier** [comment]
Thanks for your detailed, well-written and very helpful Pull-request (und herzliche Grüße aus Bayern nach Toronto!). I have merged your contribution to the project and will update the R-package on CRAN.

I will address the negative AppVeyor check, but i assume it to be within its settings rather than the R-code itself (which is struggling quite often...). However, i felt free to update the MD5 checksums for your contributed files and changed both time and file size for the maximum possible request for your functions: I tests them multiple times and it took only about four minutes, but `qUUID(n = 100000)` requires about 9.9MB space (instead of 400kB).

I appreciate your wonderful work and once again: Thanks for your time and effort!

**Comment by hyginn** [comment]
**Thanks!**

Much appreciated. That was fun.

* Interesting that appveyor checks fail whereas the Windows system on CRAN succeeds. There was a recent discussion on R-help that mentioned the need for docker images of the CRAN check systems, since it is not uncommon for people to find failed checks on CRAN that succeeded at home. Fortunately, this case is the other way around. But the need to make check systems portable and reproducible is certainly there.
* Thanks for updating `MD5` - I overlooked that.
- Re. the times - I extrapolated from `qrandom()` since the time will be dominated by the network connection which should be the same. I wonder why mine are now a bit faster than what you had. Anyway: obtaining these numbers in Toronto would be oranges to your apples :-)
- Re. the size: that made me wonder: a 1e5 character vector with one UUID repeated is indeed 800144 bytes. I then checked and found that `object.size()` changes depending on the complexity of the elements! Sampling from 10 UUIDs is 801008 bytes, 100: 809648 bytes, 1000: 896048. ... Testing this:

```R
f <- function(n) {
  # n random 36 character strings
  rs <- function(x) { paste0(sample(letters, 36, replace = TRUE),
                             collapse="") }
  x <- sapply(1:n, FUN = rs)
  return(x)
}

sapply(0:5, FUN = function(x) { object.size(rep(f(10^x), 10^(5-x))) })
# [1]   800144   801008   809648   896048  1760048 10400048

# whereas ...
sapply(0:5, FUN = function(x) { object.size(rep(runif(10^x), 10^(5-x))) })
# [1] 800048 800048 800048 800048 800048 800048
```
   I then found section 1.10 of [R-internals](https://cran.r-project.org/doc/manuals/r-release/R-ints.pdf) which confirms that there is indeed a global `CHARSXP` cache which ensures strings with the same contents share storage. This explains it all. Who knew.

I'll open two issues a bit later. If you ever need two more hands on the code or eyes on the docs, just let me know.

B.

**Comment by skoestlmeier** [comment]
Time certainly flies and over 1.5 month elapsed since your first comment on this package. Thanks again for your contribution; i updated your improvements in the official CRAN package which is not possible more than once a month (and this is the reason why i set myself a reminder after a whole month has passed).

The fact with `object.size()` is worth a look into the R internals - i did not expect how `R` handles this internally; very interesting!

My question up to now is regarding the **two** issues you have planed to open. We already fixed **one** of your reported issues (#2). Is there anything left to do which does not work as expected? Feel free to open another issue if you found anything, i will look at it immediately.

**Pull request merged**
